version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8082:80"
    depends_on:
      - db
      - redis

  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: advanced_messaging_system
      MYSQL_USER: bakill3
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
